### ISSUE TITLE
Some types are lost

### ISSUE THREAD

**Issue by wolfv** [kinnison/marked-yaml#13]
I think in marked-yaml, some types are currently "lost".

For example, the following:

```yaml
foo: 5
# or
foo_str: "5"  # (the `"` are stripped in the YAML parsing)
```

are different types in YAML. However, in marked-yaml they end up being the same (ScalarNode). The conversion from `foo_str.as_i64` works fine - which IMO it shouldn't since it's a "forced" string. 

Not sure if that's something you'd consider. It would mean we have to track the types as they come from the Yaml loader.
